---
- name: Dev Environment Setup
  hosts: localhost
  become: true
  
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - node
        - zsh
        - rust
  tasks:
    - include:
      - node
      - zsh
      - rust

    

