---
- name: Dev Environment Setup
  hosts: localhost
  become: true
  
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      tags:
        - node
        - zsh
        - rust
  tasks:
    - include: tasks/zsh-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/rust-setup.yml

    

