- name: Install zsh
  apt:
    name: zsh
    state: present
  tags: zsh

- name: Change shell
  shell: chsh -s `which zsh`
  tags: zsh

- name: Install oh-my-zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags: zsh

- name: Install zsh plugin autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
  tags: zsh

- name: update zshrc
  shell: sed -i 's/(git/(git zsh-autosuggestions' ~/.zshrc'
  tags: zsh