- name: Remove conflicting packages
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
  tags:
    - install
    - core
    - docker

- name: Install prerequisites and set up Docker repository
  block:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install ca-certificates and curl
      apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Create directory for apt keyring
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Download Docker GPG key
      shell: >
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      args:
        creates: /etc/apt/keyrings/docker.asc

    - name: Make Docker GPG key readable
      file:
        path: /etc/apt/keyrings/docker.asc
        mode: '0755'
        owner: root
        group: root

    - name: Add Docker repository to Apt sources
    
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu mantic stable"
        create: yes
        state: present
        

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
  become: true
  
- name: Additional Docker installation using apt-get
  block:
    - name: Install Docker packages using apt-get
      shell: >
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  become: true
